name: Build extension

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version:
          - 22.x
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: 'Use Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v4
        with:
          node-version: '${{ matrix.node-version }}'
          cache: npm
      
      - name: Prepare for build
        run: npm ci

      - name: Build
        run: npm run build

      - name: Read manifest
        run: echo "MANIFEST_JSON=$(jq -c . < manifest.json)" >> $GITHUB_ENV
      
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: .
          omitBody: true
          tag: '${{ fromJson(env.MANIFEST_JSON).version }}'
